#!/usr/bin/env python3
"""
Render a 3-colour (paper / black / one spot ink) page from an sRGB source.

Per page:
  1. find paper, black and spot cluster centres from the page's *pure* pixels
     (low-saturation extremes for paper and black; high-saturation extreme
     for the spot).
  2. classify pixels:
       spot  = γ from linear decomposition > T_SPOT
       black = luma < LUMA_BLACK AND saturation < SAT_BLACK AND not spot
       else  = white paper.
  3. write a 4-colour palette TIFF (LZW), no dither.

If `--check` is given, only print the dominant-hue percentage of saturated
pixels and exit (0 if ≥ TOP1_MIN, 1 otherwise) — no output file written.

Usage:
  spot_render.py --check <src>
  spot_render.py <src_rgb> <out_tiff> [<k_bilevel>]

  If <k_bilevel> is given it overrides the luma-threshold black detection.
  That K plate must already be cropped to the same dimensions as <src_rgb>
  (typically generated upstream from the source PNG via the convert.py +
  K-separate + threshold + crop chain). Using K-bilevel preserves halftone
  dot patterns (e.g. 25 % screened backgrounds) that the luma threshold
  would smooth out.
"""
import sys
import numpy as np
from PIL import Image
Image.MAX_IMAGE_PIXELS = None

SAT_FLOOR  = 60         # pixel saturation to count toward hue histogram
HUE_BIN_DEG = 15
ARC_MIN    = 95         # top bin + 2 adjacent bins must hold this % to be "spot"
T_SPOT     = 0.40
LUMA_BLACK = 100
SAT_BLACK  = 60

# Canonical sRGB triples emitted by the color pipeline
# (USWebCoatedSWOP.icc → AdobeRGB1998.icc) for each pure CMYK ink and pair.
# Generated by canonical_inks.py — clamp Y overflow to 255.
CANONICAL_INK_RGB = {
    'K':  (39,  36,  37),
    'C':  (0,   172, 236),
    'M':  (202, 0,   136),
    'Y':  (255, 242, 45),
    'MY': (204, 34,  41),    # red
    'MC': (50,  52,  142),   # blue
    'CY': (51,  164, 87),    # green
}
# Hue (in degrees) at which each ink combo's saturated pixels cluster.
INK_HUE = {
    'MY': 0,    # red
    'Y':  60,
    'CY': 120,  # green
    'C':  180,  # cyan
    'MC': 240,  # blue
    'M':  300,  # magenta / pink
}


def closest_ink(hue_deg):
    """Map an observed hue (0..360) to its closest canonical ink combo."""
    best, best_d = None, 1e9
    for name, h in INK_HUE.items():
        d = abs((hue_deg - h + 540) % 360 - 180)
        if d < best_d:
            best, best_d = name, d
    return best


def top_hue_arc_percent(rgb):
    """% of saturated pixels in the most-populated 15° hue bin plus its
    two neighbours (hue wraps around 360°). Captures a single ink whose
    anti-aliased edges spill into adjacent hue bins."""
    r, g, b = rgb[..., 0].astype(int), rgb[..., 1].astype(int), rgb[..., 2].astype(int)
    mx = np.maximum.reduce([r, g, b])
    mn = np.minimum.reduce([r, g, b])
    sat = mx - mn
    mask = sat >= SAT_FLOOR
    if not mask.any():
        return 0.0, 0.0
    rs, gs, bs = r[mask], g[mask], b[mask]
    mxs, mns = mx[mask], mn[mask]
    delta = mxs - mns
    hue = np.zeros_like(rs, dtype=float)
    isR = (mxs == rs)
    isG = (mxs == gs) & ~isR
    isB = (mxs == bs) & ~isR & ~isG
    hue[isR] = ((gs[isR] - bs[isR]) / delta[isR]) % 6
    hue[isG] = ((bs[isG] - rs[isG]) / delta[isG]) + 2
    hue[isB] = ((rs[isB] - gs[isB]) / delta[isB]) + 4
    hue *= 60
    bins = 360 // HUE_BIN_DEG
    hist, _ = np.histogram(hue, bins=bins, range=(0, 360))
    peak = int(hist.argmax())
    left  = (peak - 1) % bins
    right = (peak + 1) % bins
    arc = hist[peak] + hist[left] + hist[right]
    arc_pct = 100 * arc / mask.sum()
    # mass-weighted hue (deg) of the 3-bin arc → maps to canonical ink
    centers = np.array([peak, left, right]) * HUE_BIN_DEG + HUE_BIN_DEG / 2
    weights = np.array([hist[peak], hist[left], hist[right]])
    # circular mean to handle 360°-wrap
    rad = np.deg2rad(centers)
    avg_hue = np.rad2deg(np.arctan2((np.sin(rad) * weights).sum(),
                                    (np.cos(rad) * weights).sum())) % 360
    return arc_pct, avg_hue


def find_centers(pts):
    """Locate the page's actual paper/black/spot in RGB space.
    These are used ONLY for the linear decomposition (so anti-aliased pink
    edges decompose as `mostly paper + a little spot`, not as
    `mostly paper + a little black`). The OUTPUT pixels are always the
    canonical sRGB triples from CANONICAL_INK_RGB / pure white / pure black.
    """
    luma = pts @ np.array([0.299, 0.587, 0.114])
    sat = pts.max(1) - pts.min(1)
    low_sat = sat < 25
    paper_mask = low_sat & (luma > np.percentile(luma[low_sat], 80))
    black_mask = low_sat & (luma < np.percentile(luma[low_sat], 5))
    spot_mask  = sat > np.percentile(sat, 99)
    return [
        pts[paper_mask].mean(0) if paper_mask.any() else np.array([245., 245., 245.]),
        pts[black_mask].mean(0) if black_mask.any() else np.array([20., 20., 20.]),
        pts[spot_mask].mean(0)  if spot_mask.any()  else np.array([200., 40., 50.]),
    ]


def render(src_path, out_path, k_bilevel_path=None):
    img = np.array(Image.open(src_path).convert("RGB"), dtype=np.float32)
    H, W, _ = img.shape
    px = img.reshape(-1, 3)
    rng = np.random.default_rng(0)
    sample = px[rng.choice(len(px), min(50_000, len(px)), replace=False)]
    P_c, K_c, S_c = find_centers(sample)

    # Pick the canonical sRGB for whichever ink (M, Y, MY=red, MC=blue, ...)
    # the page's spot center matches — by hue.
    _, avg_hue = top_hue_arc_percent(np.array(Image.open(src_path).convert("RGB")))
    ink_name = closest_ink(avg_hue)
    spot_canonical = CANONICAL_INK_RGB[ink_name]

    A = np.column_stack([K_c - P_c, S_c - P_c])
    Minv = np.linalg.pinv(A)
    gamma = ((px - P_c) @ Minv.T)[:, 1].reshape(H, W).clip(0, 1)
    spot_mask = gamma > T_SPOT

    if k_bilevel_path:
        k_arr = np.array(Image.open(k_bilevel_path).convert("L"))
        # K bilevel: 0 = ink, 255 = paper
        black_mask = (k_arr == 0) & ~spot_mask
    else:
        luma_img = img @ np.array([0.299, 0.587, 0.114])
        sat_img  = img.max(2) - img.min(2)
        black_mask = (luma_img < LUMA_BLACK) & (sat_img < SAT_BLACK) & ~spot_mask

    out = np.full((H, W, 3), 255, dtype=np.uint8)
    out[spot_mask]  = spot_canonical
    out[black_mask] = [0, 0, 0]

    pal_img = Image.new("P", (1, 1))
    pal_img.putpalette([255, 255, 255,
                        0, 0, 0,
                        spot_canonical[0], spot_canonical[1], spot_canonical[2],
                        0, 0, 0] + [0] * (256 * 3 - 12))
    out_img = Image.fromarray(out).quantize(palette=pal_img, dither=Image.Dither.NONE)
    out_img.save(out_path, compression="tiff_lzw")
    return ink_name, spot_canonical


def main():
    args = sys.argv[1:]
    if "--check" in args:
        args.remove("--check")
        rgb = np.array(Image.open(args[0]).convert("RGB"))
        pct, _ = top_hue_arc_percent(rgb)
        print(f"{pct:.1f}")
        sys.exit(0 if pct >= ARC_MIN else 1)

    if len(args) not in (2, 3):
        sys.exit("usage: spot_render.py [--check] <src> [<out_tiff> [<k_bilevel>]]")
    k_path = args[2] if len(args) == 3 else None
    ink_name, rgb = render(args[0], args[1], k_path)
    print(f"ink={ink_name} rgb({rgb[0]},{rgb[1]},{rgb[2]})  → {args[1]}")


if __name__ == "__main__":
    main()
